# Generated by Django 5.2.3 on 2025-06-24 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='eligibility_criteria',
            field=models.CharField(choices=[('all_students', 'All Students'), ('international_students', 'International Students'), ('national_students', 'National Students'), ('department', 'Specific Department'), ('faculty', 'Specific Faculty'), ('option', 'Specific Option'), ('level', 'Specific Level'), ('class', 'Specific Class'), ('intake', 'Specific Intake'), ('staff', 'Staff'), ('administrators', 'Administrators'), ('guild', 'Guild Council'), ('all', 'All')], default='all', max_length=100),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Administrator'), ('guild', 'Guild Council')], max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('faculty', models.CharField(blank=True, max_length=100)),
                ('option', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('intake', models.CharField(blank=True, max_length=50)),
                ('student_class', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
