# Generated by Django 5.2.3 on 2025-06-26 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_feedback_pasteventpost_postcomment_postreaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='comment',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='post',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='event_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.pasteventpost'),
            preserve_default=False,
        ),
    ]
