# Generated by Django 5.2.3 on 2025-06-26 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_comment_postcomment_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastEventPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_event_images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.pasteventpost')),
            ],
        ),
    ]
