# Generated by Django 5.2.3 on 2025-06-26 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_pasteventpostimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasteventpost',
            name='event',
        ),
        migrations.RemoveField(
            model_name='pasteventpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pasteventpost',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='pasteventpost',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pasteventpost',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pasteventpost',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
